method: 'SimVP'

# model
spatio_kernel_enc: 3
spatio_kernel_dec: 3
# model_type = None  # define `model_type` in args
hid_S: 64
hid_T: 512
N_T: 8
N_S: 4

# training
lr: 0.001
batch_size: 8
val_batch_size: 16
drop_path: 0
sched: 'CosineAnnealingLR'
val_batch_size: 16
num_workers: 4
data_root: /vast/snm6477/DL_Finals/Dataset_Student
distributed: false
model_path: ./checkpoints/simvp_checkpoint.pth

# Fine tuning
num_classes: 49
ft_lr: 0.001
ft_num_epochs: 100
use_mask: true
split_mask: true